import Head from "next/head";
import Image from "next/image";
import moment from "moment";
import React from "react";
import { useRouter } from "next/router";
import { CheckoutForm } from "@/src/components/Checkout Form";
import { Footer } from "@/src/components/Footer";
import { getData } from "@/src/utils/fetch";
import { Navbar } from "@/src/components/Navbar";
import { handlerFormatDate } from "@/src/utils/date format";
import { handlerFormatCurrency } from "@/src/utils/currency";

export default function Checkout({ detail }) {
	const router = useRouter();
	const { ticketID } = router.query;

	return (
		<>
			<Head>
				<title>Semina | Checkout</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" type="image/svg+xml" href="/images/Logo.svg" />
			</Head>

			<section className="bg-navy">
				<Navbar />
			</section>

			<section className="bg-navy">
				<div className="checkout container">
					<div className="text-center checkout-title">
						Invest In Yourself
					</div>

					<div className="event-details container d-flex flex-wrap justify-content-lg-center align-items-center gap-5">
						<Image
							src={`${process.env.NEXT_PUBLIC_API_URL}/${detail?.image?.name}`}
							className="event-image"
							alt="semina"
							width={400}
                            height={560}
                            style={{objectFit: 'cover', objectPosition: 'center'}}
						/>

						<div className="d-flex flex-column gap-3">
							<h5>{detail.title}</h5>

							<div className="d-flex align-items-center gap-3">
								<Image
									src={"/images/Marker White.svg"}
									alt=""
									width={25}
									height={25}
								/>
								<span>{detail.venueName}</span>
							</div>
							<div className="d-flex align-items-center gap-3">
								<Image
									src={"/images/Time White.svg"}
									alt=""
									width={25}
									height={25}
								/>
								<span>{moment(detail.date).format("HH.MM A")}</span>
							</div>
							<div className="d-flex align-items-center gap-3">
								<Image
									src={"/images/Calendar White.svg"}
									alt=""
									width={25}
									height={25}
								/>
								<span>{handlerFormatDate(detail.date)}</span>
							</div>
						</div>
						<div className="total-price">
							{detail?.tickets?.map((ticket) => (
								<React.Fragment key={ticket._id}>
									{ticket._id === ticketID
										? ticket.price === 0
											? "Free"
											: handlerFormatCurrency(ticket.price)
										: null}
								</React.Fragment>
							))}
						</div>
					</div>

					<CheckoutForm tickets={detail.tickets} />
				</div>
			</section>
			<Footer />
		</>
	)
}

export async function getServerSideProps(context) {
	const { token } = context.req.cookies;
	if (!token) {
		return {
			redirect: {
				destination: "/signin",
				permanent: false
			}
		}
	}

	const response = await getData(
		`${process.env.NEXT_PUBLIC_API_URL}/participants/events/${context.params.id}`
	)
	return {
		props: {
			detail: response.data
		}
	}
}