const ERROR_FETCHING_PAYMENTS = '/redux/payments/ERROR_FETCHING_PAYMENTS';
const SET_KEYWORD = '/redux/payments/SET_KEYWORD';
const START_FETCHING_PAYMENTS = '/redux/payments/START_FETCHING_PAYMENTS';
const SUCCESS_FETCHING_PAYMENTS = '/redux/payments/SUCCESS_FETCHING_PAYMENTS';

export {
    ERROR_FETCHING_PAYMENTS,
    SET_KEYWORD,
    START_FETCHING_PAYMENTS,
    SUCCESS_FETCHING_PAYMENTS
}