const ERROR_FETCHING_TALENTS = '/redux/talents/ERROR_FETCHING_TALENTS';
const SET_KEYWORD = '/redux/talents/SET_KEYWORD';
const START_FETCHING_TALENTS = '/redux/talents/START_FETCHING_TALENTS';
const SUCCESS_FETCHING_TALENTS = '/redux/talents/SUCCESS_FETCHING_TALENTS';

export {
    ERROR_FETCHING_TALENTS,
    SET_KEYWORD,
    START_FETCHING_TALENTS,
    SUCCESS_FETCHING_TALENTS
}