const START_FETCHING_LISTS_CATEGORIES = '/redux/lists/START_FETCHING_LISTS_CATEGORIES';
const SUCCESS_FETCHING_LISTS_CATEGORIES = '/redux/lists/SUCCESS_FETCHING_LISTS_CATEGORIES';
const ERROR_FETCHING_LISTS_CATEGORIES = '/redux/lists/ERROR_FETCHING_LISTS_CATEGORIES';

const START_FETCHING_LISTS_TALENTS = '/redux/lists/START_FETCHING_LISTS_TALENTS';
const SUCCESS_FETCHING_LISTS_TALENTS = '/redux/lists/SUCCESS_FETCHING_LISTS_TALENTS';
const ERROR_FETCHING_LISTS_TALENTS = '/redux/lists/ERROR_FETCHING_LISTS_TALENTS';

const START_FETCHING_LISTS_EVENTS = '/redux/lists/START_FETCHING_LISTS_EVENTS';
const SUCCESS_FETCHING_LISTS_EVENTS = '/redux/lists/SUCCESS_FETCHING_LISTS_EVENTS';
const ERROR_FETCHING_LISTS_EVENTS = '/redux/lists/ERROR_FETCHING_LISTS_EVENTS';

export {
    ERROR_FETCHING_LISTS_CATEGORIES,
    ERROR_FETCHING_LISTS_EVENTS,
    ERROR_FETCHING_LISTS_TALENTS,
    SUCCESS_FETCHING_LISTS_CATEGORIES,
    SUCCESS_FETCHING_LISTS_EVENTS,
    SUCCESS_FETCHING_LISTS_TALENTS,
    START_FETCHING_LISTS_CATEGORIES,
    START_FETCHING_LISTS_EVENTS,
    START_FETCHING_LISTS_TALENTS
}