const START_FETCHING_EVENTS = '/redux/events/START_FETCHING_EVENTS';
const SUCCESS_FETCHING_EVENTS = '/redux/events/SUCCESS_FETCHING_EVENTS';
const ERROR_FETCHING_EVENTS = '/redux/events/ERROR_FETCHING_EVENTS';
const SET_KEYWORD = '/redux/events/SET_KEYWORD';
const SET_CATEGORY = '/redux/events/SET_CATEGORY';
const SET_TALENT = '/redux/events/SET_TALENT';

export {
    ERROR_FETCHING_EVENTS,
    SET_CATEGORY,
    SET_KEYWORD,
    SET_TALENT,
    START_FETCHING_EVENTS,
    SUCCESS_FETCHING_EVENTS
}