import Head from "next/head";
import { Brand } from "@/src/components/Brand";
import { CardEvent } from "@/src/components/Card Event";
import { Footer } from "@/src/components/Footer";
import { getData } from "@/src/utils/fetch";
import { Header } from "@/src/components/Header";
import { Statistics } from "@/src/components/Statistics";
import { Stories } from "@/src/components/Stories";

export default function Home({ data }) {
  return (
		<>
			<Head>
				<title>Semina</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" type="image/svg+xml" href="/images/Logo.svg" />
			</Head>
			<Header />
			<Brand />
			<CardEvent
				data={data}
				title={"Featured Events"}
				subTitle={"Grow Together"}
			/>
			<Stories />
			<Statistics />
			<Footer />
		</>
  )
}

export async function getServerSideProps(context) {
  const response = await getData(`${process.env.NEXT_PUBLIC_API_URL}/participants/events`, null, null)
  return {
    props: {
      data: response.data ?? null
    }
  }
}