import Head from "next/head";
import { Brand } from "@/src/components/Brand";
import { Navbar } from "@/src/components/Navbar";
import { RegisterForm } from "@/src/components/Register Form";

export default function Register() {
	return (
		<>
			<Head>
				<title>Semina | Sign Up</title>
				<meta name="description" content="Generated by create-next-app" />
				<link rel="icon" type="image/svg+xml" href="/images/Logo.svg" />
			</Head>

			<section className="bg-navy">
				<Navbar />
			</section>

			<section className="login header bg-navy">
				<div className="container">
					<div className="row row-cols-md-12 row-cols-1 d-flex justify-content-center align-items-center hero">
						<div className="col-md-6">
							<div className="hero-headline text-start">
								Expand Your <br className="d-none d-md-block" />
								Knowledge & Skills
							</div>
							<p className="hero-paragraph text-start">
								We provide the best events to help you improve{" "}
								<br className="d-none d-lg-block" />
								your skills in the field of technology
							</p>
						</div>
						<div className="col-md-6">
							<RegisterForm />
						</div>
					</div>
				</div>
			</section>

			<Brand className={"pt-0 bg-navy"} />
		</>
	)
}