import Head from "next/head";
import { Brand } from "@/src/components/Brand";
import { LoginForm } from "@/src/components/Login Form";
import { Navbar } from "@/src/components/Navbar";

export default function Login() {
    return (
        <>
            <Head>
                <title>Semina | Sign In</title>
                <meta name="description" content="Generated by create-next-app" />
                <link rel="icon" type="image/svg+xml" href="/images/Logo.svg" />
            </Head>

            <section className="bg-navy">
                <Navbar />
            </section>
            <section className="login header bg-navy">
                <div className="container">
                    <div className="d-flex flex-column align-items-center hero gap-5">
                        <div className="">
                            <div className="hero-headline text-start">Sign In</div>
                        </div>
                        <LoginForm />
                    </div>
                </div>
            </section>
            <Brand />
        </>
    )
}

export async function getServerSideProps(context) {
    const { token } = context.req.cookies;
    if (token) {
        return {
            redirect: {
                destination: '/',
                permanent: false
            }
        }
    }

    return {
        props: {}
    }
}