const START_FETCHING_ORDERS = 'redux/orders/START_FETCHING_ORDERS';
const SUCCESS_FETCHING_ORDERS = 'redux/orders/SUCCESS_FETCHING_ORDERS';
const ERROR_FETCHING_ORDERS = 'redux/orders/ERROR_FETCHING_ORDERS';
const SET_DATE = 'redux/orders/SET_DATE';
const SET_PAGE = 'redux/orders/SET_PAGE';

export {
    ERROR_FETCHING_ORDERS,
    SET_DATE,
    SET_PAGE,
    START_FETCHING_ORDERS,
    SUCCESS_FETCHING_ORDERS
}